# Generated by Django 5.0.4 on 2024-04-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
